### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by rleh** [nerdclub-tfg/signal-bot-jython#8]
I think the [AGPLv3 (GNU Affero General Public License)](https://www.gnu.org/licenses/agpl-3.0.txt) is more suitable than GPLv3 for this server-like software.
Why? See [here](https://www.gnu.org/licenses/why-affero-gpl.en.html) [(same in german)](https://www.gnu.org/licenses/why-affero-gpl.de.html) or [here](http://stackoverflow.com/a/2127313).

**Comment by Turakar** [comment]
That's true. I'll change that.
